server:
  port: 5555

spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: zuul-demo

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
    # 重要！如果不指定IP，虽然能注册成功，但是无法通过“服务名”调用！
    ip-address: 127.0.0.1
    # hostname: localhost
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}:v@project.version@

ribbon:
  ConnectTimeout: 10000 # 请求连接的超时时间
  ReadTimeout: 10000 # 请求处理的超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
